// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnthjabxkmgmbuquefyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1udGhqYWJ4a21nbWJ1cXVlZnl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzY1MjQsImV4cCI6MjA2NzY1MjUyNH0.QH73C4JdulYOf0f66GjkGahFdg8sxKdXhP-7BZE5wE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});